---
services:
  napari-env:
    image: gnasello/napari-env:latest
    security_opt:
      - seccomp:unconfined # for terminal to work
    volumes:
      - $HOME_RESEARCHER:/config/researcher_home
    ports:
      - '3000'
    env_file:
      - stack.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 'all'
              count: 1
              capabilities: [compute,video,graphics,utility]
              # device_ids: ['0', '3']