services:
  ilastik-env:
    image: gnasello/ilastik-env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ilastik-${UNAME}.entrypoints=web"
      - "traefik.http.routers.ilastik-${UNAME}.rule=Host(`ilastik-${UNAME}.${QUBEIP}.nip.io`)"
      - "traefik.http.services.ilastik-${UNAME}.loadbalancer.server.port=3000"

    environment:
      - CONTAINER_URL=http://ilastik-${UNAME}.${QUBEIP}.nip.io:${QUBEPORT}
      - CUSTOM_USER=${UNAME}
      - PASSWORD
      - QUBEPORT
      - QUBEIP
      - UNAME
      
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true