---
version: "3"
services:
  sc-py-env:
    image: gnasello/sc-py-env:latest
    volumes:
      - $HOME_RESEARCHER:/home/jovyan/researcher_home
    ports:
      - '8888'
    user: root
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - GRANT_SUDO=yes
    env_file:
      - stack.env
