services:
  sc-py:
    image: gnasello/sc-py-env:latest    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sc-py_${UNAME}.rule=PathPrefix(`/${UNAME}/sc-py-env`)"
      - "traefik.http.services.sc-py_${UNAME}.loadbalancer.server.port=8888"
      - "traefik.http.routers.sc-py_${UNAME}.entrypoints=web"
    user: root
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - CONTAINER_URL=${DOMAIN_URL}/${UNAME}/sc-py-env/lab?token=${JUPYTER_TOKEN}
      - DOMAIN_URL
      - GRANT_SUDO=yes
      - NB_GID=100
      - NB_UID=1000
      - NOTEBOOK_ARGS='--NotebookApp.base_url=/${UNAME}/sc-py-env'
      - JUPYTER_TOKEN # openssl rand -hex 32
      - UNAME
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
