---
services:
  sc-py-env-gpu:
    image: gnasello/sc-py-env-gpu:latest
    volumes:
      - $HOME_RESEARCHER:/home/jovyan/researcher_home
    user: root
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - GRANT_SUDO=yes
    ports:
      - '8888'
    env_file:
      - stack.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 'all'
              count: 1
              # device_ids: ['0', '3']
              capabilities: [gpu]