services:
  ofpv:
    image: gnasello/ofpv-env:latest    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ofpv-${UNAME}.entrypoints=web"
      - "traefik.http.routers.ofpv-${UNAME}.rule=Host(`ofpv-${UNAME}.${QUBEIP}.nip.io`)"
      - "traefik.http.services.ofpv-${UNAME}.loadbalancer.server.port=3000"

    environment:
      - CONTAINER_URL=http://ofpv-${UNAME}.${QUBEIP}.nip.io:${QUBEPORT}
      - CUSTOM_USER=${UNAME}
      - PASSWORD
      - QUBEPORT
      - QUBEIP
      - UNAME

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
